# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[global.limits]
forms = 32768
json = 1048576
msgpack = 1048576

[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="

[production]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
assets_dir = "dist/"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="